disabled = false
languageCode = "fr"
languageName = "Français"
weight = 1
title = "NoNames"

[params]
displayName = "FR"
isoCode = "fr"
rtl = false
dateFormat = "02/01/2006"
# dateFormat = "2 January 2006"
description = "Blog personnel sur l'informatique et un peu de bidouillage"

[params.author]
name = "NoNames"
image = "logo.png"
headline = "Blog personnel sur l'informatique et un peu de bidouillage"
bio = "Spécialiste des outils en ligne de commande"
links = [{ github = "https://github.com/0xNoNames" }]
