disabled = false
languageCode = "fr"
languageName = "Français"
weight = 1
title = "NoNames"

[params]
displayName = "FR"
isoCode = "fr"
dateFormat = "02/01/2006"
# copyright = "© 2024 - { year } NoNames"
description = "Blog personnel sur l'informatique et un peu de bidouillage"

[params.author]
name = "NoNames"
image = "logo.gif"
headline = "Blog personnel sur l'informatique et un peu de bidouillage"
bio = "Expert en CLI"
links = [{ github = "https://github.com/0xNoNames" }]
