[[main]]
name = "Articles"
pre = "code"
pageRef = "articles"
weight = 10

[[main]]
name = "Cat√©gories"
pre = "bars"
pageRef = "categories"
weight = 20

[[main]]
name = "Tags"
pre = "tag"
pageRef = "tags"
weight = 30
