colorScheme = "dracula"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false
defaultBackgroundImage = "logo_full.png"
defaultFeaturedImage = "logo_full.png"

[header]
layout = "fixed"

[footer]
showAppearanceSwitcher = false
showMenu = false
showCopyright = false
showThemeAttribution = false

[homepage]
layout = "background"
homepageImage = "logo_full.png"
showRecent = true
showRecentItems = 3
showMoreLink = true
showMoreLinkDest = "/articles/"
showCards = true
layoutBackgroundBlur = true

[article]
showDateUpdated = true
showAuthorBottom = false
showHero = true
heroStyle = "basic"
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
seriesOpened = false
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 3
showTaxonomies = true
showWordCount = true
showComments = true
showZenMode = false
showViews = true
showLikes = true

[list]
showHero = false
heroStyle = "background"
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showSummary = true
showTableOfContents = false
showCards = true
groupByYear = true

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showHero = false
heroStyle = "background"
showBreadcrumbs = true
cardView = true

[term]
showHero = false
heroStyle = "background"
showBreadcrumbs = true
groupByYear = true

[firebase]
apiKey = "AIzaSyDoym1aKHOFurPD3FHik5yyczoqHZTfBBw"
authDomain = "nonames-blog.firebaseapp.com"
projectId = "nonames-blog"
storageBucket = "nonames-blog.firebasestorage.app"
messagingSenderId = "689468923711"
appId = "1:689468923711:web:9e8b14b58a84a28244fd8a"
measurementId = ""
