colorScheme = "dracula"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
highlightCurrentMenuArea = true
smartTOC = true

[header]
layout = "fixed-fill-blur"

[footer]
showMenu = true
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = "showRecent"
showRecentItems = "3"
showMoreLink = false
showMoreLinkDest = "/articles/"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false
homepageImage = ""

[article]
showDate = true
showViews = true
showLikes = true
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = true
showAuthorBottom = true
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = true
showZenMode = false
showComments = true

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false
heroStyle = "basic"

[firebase]
apiKey = "AIzaSyDoym1aKHOFurPD3FHik5yyczoqHZTfBBw"
authDomain = "nonames-blog.firebaseapp.com"
projectId = "nonames-blog"
storageBucket = "nonames-blog.firebasestorage.app"
messagingSenderId = "689468923711"
appId = "1:689468923711:web:9e8b14b58a84a28244fd8a"
measurementId = ""
